-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.attendance
(
    attendance_id bigserial NOT NULL,
    student_id bigint NOT NULL,
    course_id bigint NOT NULL,
    date date NOT NULL,
    status attendance_status NOT NULL,
    reason_note text COLLATE pg_catalog."default",
    recorded_by character varying(50) COLLATE pg_catalog."default",
    recorded_at timestamp with time zone DEFAULT now(),
    excused_by character varying(50) COLLATE pg_catalog."default",
    excused_at timestamp with time zone,
    deleted_at timestamp with time zone,
    slot_id bigint,
    CONSTRAINT attendance_pkey PRIMARY KEY (attendance_id),
    CONSTRAINT attendance_student_id_course_id_date_key UNIQUE (student_id, course_id, date)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    audit_id bigserial NOT NULL,
    entity_name text COLLATE pg_catalog."default" NOT NULL,
    entity_id bigint,
    action character varying(20) COLLATE pg_catalog."default" NOT NULL,
    payload jsonb,
    performed_by character varying(50) COLLATE pg_catalog."default",
    performed_at timestamp with time zone DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS public.class_groups
(
    class_group_id bigserial NOT NULL,
    school_year_id bigint NOT NULL,
    grade_level smallint NOT NULL,
    section character varying(10) COLLATE pg_catalog."default" NOT NULL,
    classroom_id bigint,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT class_groups_pkey PRIMARY KEY (class_group_id),
    CONSTRAINT class_groups_school_year_id_grade_level_section_key UNIQUE (school_year_id, grade_level, section)
);

CREATE TABLE IF NOT EXISTS public.classrooms
(
    classroom_id bigserial NOT NULL,
    name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    building character varying(80) COLLATE pg_catalog."default",
    capacity integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT classrooms_pkey PRIMARY KEY (classroom_id),
    CONSTRAINT classrooms_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.course_instances
(
    course_instance_id bigserial NOT NULL,
    subject_id bigint NOT NULL,
    grade_level smallint NOT NULL,
    school_year_id bigint NOT NULL,
    weekly_hours integer NOT NULL DEFAULT 0,
    course_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    course_name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT course_instances_pkey PRIMARY KEY (course_instance_id),
    CONSTRAINT course_instances_course_code_school_year_id_key UNIQUE (course_code, school_year_id),
    CONSTRAINT course_instances_subject_id_grade_level_school_year_id_key UNIQUE (subject_id, grade_level, school_year_id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    course_id bigserial NOT NULL,
    course_instance_id bigint NOT NULL,
    class_group_id bigint NOT NULL,
    teacher_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT courses_pkey PRIMARY KEY (course_id),
    CONSTRAINT courses_course_instance_id_class_group_id_teacher_id_key UNIQUE (course_instance_id, class_group_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS public.disciplinary_records
(
    disciplinary_id bigserial NOT NULL,
    student_id bigint NOT NULL,
    date_happened date NOT NULL,
    category disciplinary_level NOT NULL,
    description text COLLATE pg_catalog."default",
    recorded_by character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    expires_at date,
    deleted_at timestamp with time zone,
    CONSTRAINT disciplinary_records_pkey PRIMARY KEY (disciplinary_id)
);

CREATE TABLE IF NOT EXISTS public.enrollments
(
    enrollment_id bigserial NOT NULL,
    student_id bigint NOT NULL,
    class_group_id bigint NOT NULL,
    school_year_id bigint NOT NULL,
    enrolled_at timestamp with time zone DEFAULT now(),
    active boolean DEFAULT true,
    CONSTRAINT enrollments_pkey PRIMARY KEY (enrollment_id),
    CONSTRAINT enrollments_student_id_class_group_id_school_year_id_key UNIQUE (student_id, class_group_id, school_year_id)
);

CREATE TABLE IF NOT EXISTS public.grade_scheme_values
(
    value_id bigserial NOT NULL,
    scheme_id bigint NOT NULL,
    code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    label character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sort_order smallint NOT NULL,
    is_passing boolean NOT NULL,
    CONSTRAINT grade_scheme_values_pkey PRIMARY KEY (value_id),
    CONSTRAINT grade_scheme_values_scheme_id_code_key UNIQUE (scheme_id, code)
);

CREATE TABLE IF NOT EXISTS public.grade_schemes
(
    scheme_id bigserial NOT NULL,
    name character varying(40) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT grade_schemes_pkey PRIMARY KEY (scheme_id),
    CONSTRAINT grade_schemes_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.grades
(
    grade_id bigserial NOT NULL,
    student_id bigint NOT NULL,
    course_id bigint NOT NULL,
    term_id bigint NOT NULL,
    scheme_value_id bigint,
    recorded_by character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    comment text COLLATE pg_catalog."default",
    mark smallint NOT NULL DEFAULT 4,
    CONSTRAINT grades_pkey PRIMARY KEY (grade_id),
    CONSTRAINT grades_student_id_course_id_term_id_key UNIQUE (student_id, course_id, term_id)
);

COMMENT ON COLUMN public.grades.mark
    IS 'Numeric mark domain: 5=S, 4=A, 3=B, 1=J. Values 2 and 0 are unused.';

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    "timestamp" bigint NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id bigserial NOT NULL,
    created_by character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    title character varying(120) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    category character varying(40) COLLATE pg_catalog."default" NOT NULL DEFAULT 'general'::character varying,
    student_id bigint,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.school_years
(
    school_year_id bigserial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    year_start date NOT NULL,
    year_end date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT school_years_pkey PRIMARY KEY (school_year_id),
    CONSTRAINT school_years_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.students
(
    student_id bigserial NOT NULL,
    national_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(80) COLLATE pg_catalog."default" NOT NULL,
    dob date,
    address text COLLATE pg_catalog."default",
    guardian_name character varying(120) COLLATE pg_catalog."default",
    guardian_relationship character varying(60) COLLATE pg_catalog."default",
    guardian_phone character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT students_pkey PRIMARY KEY (student_id),
    CONSTRAINT students_national_id_key UNIQUE (national_id)
);

CREATE TABLE IF NOT EXISTS public.subject_areas
(
    area_id bigserial NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    code character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT subject_areas_pkey PRIMARY KEY (area_id),
    CONSTRAINT subject_areas_code_key UNIQUE (code),
    CONSTRAINT subject_areas_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    subject_id bigserial NOT NULL,
    area_id bigint NOT NULL,
    subject_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT subjects_pkey PRIMARY KEY (subject_id),
    CONSTRAINT subjects_subject_code_key UNIQUE (subject_code)
);

CREATE TABLE IF NOT EXISTS public.terms
(
    term_id bigserial NOT NULL,
    school_year_id bigint NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    sort_order smallint NOT NULL,
    is_final boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT terms_pkey PRIMARY KEY (term_id),
    CONSTRAINT terms_school_year_id_name_key UNIQUE (school_year_id, name)
);

CREATE TABLE IF NOT EXISTS public.timetable_assignments
(
    assignment_id bigserial NOT NULL,
    course_id bigint NOT NULL,
    slot_id bigint NOT NULL,
    classroom_id bigint,
    created_at timestamp with time zone DEFAULT now(),
    teacher_id character varying(50) COLLATE pg_catalog."default",
    class_group_id bigint,
    CONSTRAINT timetable_assignments_pkey PRIMARY KEY (assignment_id),
    CONSTRAINT timetable_assignments_course_id_slot_id_key UNIQUE (course_id, slot_id)
);

CREATE TABLE IF NOT EXISTS public.timetable_slots
(
    slot_id bigserial NOT NULL,
    day_of_week smallint NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    duration_minutes integer NOT NULL,
    division character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'elementary'::character varying,
    CONSTRAINT timetable_slots_pkey PRIMARY KEY (slot_id),
    CONSTRAINT timetable_slots_day_of_week_start_time_end_time_key UNIQUE (day_of_week, start_time, end_time),
    CONSTRAINT chk_timetable_slots_division CHECK (division = ANY (ARRAY['elementary'::character varying, 'secondary'::character varying, 'senior'::character varying]))
);

CREATE TABLE IF NOT EXISTS public.users
(
    national_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    username character varying(80) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role user_role NOT NULL,
    first_name character varying(80) COLLATE pg_catalog."default",
    last_name character varying(80) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (national_id),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_course_slot_fkey FOREIGN KEY (course_id, slot_id)
    REFERENCES public.timetable_assignments (course_id, slot_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_excused_by_fkey FOREIGN KEY (excused_by)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_recorded_by_fkey FOREIGN KEY (recorded_by)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.attendance
    ADD CONSTRAINT attendance_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_performed_by_fkey FOREIGN KEY (performed_by)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class_groups
    ADD CONSTRAINT class_groups_classroom_id_fkey FOREIGN KEY (classroom_id)
    REFERENCES public.classrooms (classroom_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.class_groups
    ADD CONSTRAINT class_groups_school_year_id_fkey FOREIGN KEY (school_year_id)
    REFERENCES public.school_years (school_year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_instances
    ADD CONSTRAINT course_instances_school_year_id_fkey FOREIGN KEY (school_year_id)
    REFERENCES public.school_years (school_year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_instances
    ADD CONSTRAINT course_instances_subject_id_fkey FOREIGN KEY (subject_id)
    REFERENCES public.subjects (subject_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT courses_class_group_id_fkey FOREIGN KEY (class_group_id)
    REFERENCES public.class_groups (class_group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT courses_course_instance_id_fkey FOREIGN KEY (course_instance_id)
    REFERENCES public.course_instances (course_instance_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.courses
    ADD CONSTRAINT courses_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.disciplinary_records
    ADD CONSTRAINT disciplinary_records_recorded_by_fkey FOREIGN KEY (recorded_by)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.disciplinary_records
    ADD CONSTRAINT disciplinary_records_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enrollments
    ADD CONSTRAINT enrollments_class_group_id_fkey FOREIGN KEY (class_group_id)
    REFERENCES public.class_groups (class_group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enrollments
    ADD CONSTRAINT enrollments_school_year_id_fkey FOREIGN KEY (school_year_id)
    REFERENCES public.school_years (school_year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollments_year
    ON public.enrollments(school_year_id);


ALTER TABLE IF EXISTS public.enrollments
    ADD CONSTRAINT enrollments_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_enrollments_student
    ON public.enrollments(student_id);


ALTER TABLE IF EXISTS public.grade_scheme_values
    ADD CONSTRAINT grade_scheme_values_scheme_id_fkey FOREIGN KEY (scheme_id)
    REFERENCES public.grade_schemes (scheme_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT grades_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT grades_recorded_by_fkey FOREIGN KEY (recorded_by)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT grades_scheme_value_id_fkey FOREIGN KEY (scheme_value_id)
    REFERENCES public.grade_scheme_values (value_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT grades_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grades
    ADD CONSTRAINT grades_term_id_fkey FOREIGN KEY (term_id)
    REFERENCES public.terms (term_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk_notifications_student FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (national_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subjects
    ADD CONSTRAINT subjects_area_id_fkey FOREIGN KEY (area_id)
    REFERENCES public.subject_areas (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.terms
    ADD CONSTRAINT terms_school_year_id_fkey FOREIGN KEY (school_year_id)
    REFERENCES public.school_years (school_year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.timetable_assignments
    ADD CONSTRAINT timetable_assignments_classroom_id_fkey FOREIGN KEY (classroom_id)
    REFERENCES public.classrooms (classroom_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.timetable_assignments
    ADD CONSTRAINT timetable_assignments_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.timetable_assignments
    ADD CONSTRAINT timetable_assignments_slot_id_fkey FOREIGN KEY (slot_id)
    REFERENCES public.timetable_slots (slot_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
